import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'

import Navbar from './_components/navbar/Navbar'
import Footer from './_components/footer/Footer'
const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Bankist',
  description: 'Generated by create next app',
  icons: '/Banking/favicon.ico',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div
          className=" mx-auto
          min-h-screen
          flex
          flex-col
          justify-between
          px-container-lg
          max-w-container
          xl:max-w-xl
          lg:max-w-lg
          md:max-w-md
          sm:max-w-sm
          xs:max-w-xs"
        >
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  )
}
